export const locations = {
  ADL: 'Adelaide',
  AKL: 'Auckland',
  ALG: 'Algiers',
  AMM: 'Amman',
  AMS: 'Amsterdam',
  ARI: 'Arica',
  ARN: 'Stockholm',
  ASU: 'Asunción',
  ATH: 'Athens',
  ATL: 'Atlanta',
  BAH: 'Manama',
  BCN: 'Barcelona',
  BEG: 'Belgrade',
  BEL: 'Belém',
  BEY: 'Beirut',
  BGW: 'Baghdad',
  BKK: 'Bangkok',
  BLR: 'Bangalore',
  BNA: 'Nashville',
  BNE: 'Brisbane',
  BNU: 'Blumenau',
  BOG: 'Bogotá',
  BOM: 'Mumbai',
  BOS: 'Boston',
  BRU: 'Brussels',
  BSB: 'Brasilia',
  BUD: 'Budapest',
  BUF: 'Buffalo',
  BWN: 'Bandar Seri Begawan',
  CAN: '广州',
  CBR: 'Canberra',
  CCU: 'Kolkata',
  CDG: 'Paris',
  CEB: 'Cebu',
  CFC: 'Caçador',
  CGK: 'Jakarta',
  CGO: '郑州',
  CGP: 'Chittagong',
  CKG: '重庆',
  CLT: 'Charlotte',
  CMB: 'Colombo',
  CMH: 'Columbus',
  CMN: 'Casablanca',
  CNF: 'Belo Horizonte',
  CPH: 'Copenhagen',
  CPT: 'Cape Town',
  CSX: '株洲',
  CTU: '成都',
  CUR: 'Willemstad',
  CWB: 'Curitiba',
  DAC: 'Dhaka',
  DAR: 'Dar Es Salaam',
  DEL: 'New Delhi',
  DEN: 'Denver',
  DFW: 'Dallas',
  DKR: 'Dakar',
  DME: 'Moscow',
  DMM: 'Dammam',
  DOH: 'Doha',
  DTW: 'Detroit',
  DUB: 'Dublin',
  DUR: 'Durban',
  DUS: 'Düsseldorf',
  DXB: 'Dubai',
  EDI: 'Edinburgh',
  EVN: 'Yerevan',
  EWR: 'Newark',
  EZE: 'Buenos Aires',
  FCO: 'Rome',
  FLN: 'Florianopolis',
  FOR: 'Fortaleza',
  FRA: 'Frankfurt',
  GIG: 'Rio de Janeiro',
  GND: 'St. George’s',
  GOT: 'Gothenburg',
  GRU: 'São Paulo',
  GUA: 'Guatemala City',
  GVA: 'Geneva',
  GYD: 'Baku',
  GYE: 'Guayaquil',
  HAM: 'Hamburg',
  HAN: 'Hanoi',
  HEL: 'Helsinki',
  HKG: '香港',
  HNL: 'Honolulu',
  HRE: 'Harare',
  HYD: 'Hyderabad',
  IAD: 'Ashburn',
  IAH: 'Houston',
  ICN: 'Seoul',
  IND: 'Indianapolis',
  ISB: 'Islamabad',
  IST: 'Istanbul',
  ITJ: 'Itajaí',
  JAX: 'Jacksonville',
  JIB: 'Djibouti City',
  JNB: 'Johannesburg',
  JSR: 'Jashore',
  KBP: 'Kyiv',
  KEF: 'Reykjavík',
  KGL: 'Kigali',
  KHI: 'Karachi',
  KIV: 'Chișinău',
  KIX: 'Osaka',
  KJA: 'Krasnoyarsk',
  KTM: 'Kathmandu',
  KUL: 'Kuala Lumpur',
  KWI: 'Kuwait City',
  LAD: 'Luanda',
  LAS: 'Las Vegas',
  LAX: 'Los Angeles',
  LCA: 'Nicosia',
  LED: 'Saint Petersburg',
  LHE: 'Lahore',
  LHR: 'London',
  LIM: 'Lima',
  LIS: 'Lisbon',
  LOS: 'Lagos',
  LUX: 'Luxembourg City',
  MAA: 'Chennai',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MBA: 'Mombasa',
  MCI: 'Kansas City',
  MCT: 'Muscat',
  MDE: 'Medellín',
  MEL: 'Melbourne',
  MEM: 'Memphis',
  MEX: 'Mexico City',
  MFE: 'McAllen',
  MFM: 'Macau ',
  MGM: 'Montgomery',
  MIA: 'Miami',
  MLE: 'Malé',
  MNL: 'Manila',
  MPM: 'Maputo',
  MRS: 'Marseille',
  MRU: 'Port Louis',
  MSP: 'Minneapolis',
  MUC: 'Munich',
  MXP: 'Milan',
  NAG: 'Nagpur',
  NBG: '宁波',
  NBO: 'Nairobi',
  NOU: 'Noumea',
  NRT: 'Tokyo',
  OMA: 'Omaha',
  ORD: 'Chicago',
  ORF: 'Norfolk',
  OSL: 'Oslo',
  OTP: 'Bucharest',
  PAP: 'Port',
  PBH: 'Thimphu',
  PBM: 'Paramaribo',
  PDX: 'Portland',
  PER: 'Perth',
  PHL: 'Philadelphia',
  PHX: 'Phoenix',
  PIT: 'Pittsburgh',
  PMO: 'Palermo',
  PNH: 'Phnom Penh',
  POA: 'Porto Alegre',
  PRG: 'Prague',
  PTY: 'Panama City',
  QRO: 'Queretaro',
  QWJ: 'Americana',
  RAO: 'Ribeirao Preto',
  RGN: 'Yangon',
  RIC: 'Richmond',
  RIX: 'Riga',
  ROB: 'Monrovia',
  RUH: 'Riyadh',
  RUN: 'Réunion',
  SAN: 'San Diego',
  SCL: 'Santiago',
  SEA: 'Seattle',
  SGN: 'Ho Chi Minh City',
  SHA: '上海',
  SIN: 'Singapore',
  SJC: 'San Jose',
  SJO: 'San José',
  SJP: 'São José do Rio Preto',
  SKG: 'Thessaloniki',
  SLC: 'Salt Lake City',
  SMF: 'Sacramento',
  SOD: 'Sorocaba',
  SOF: 'Sofia',
  SSA: 'Salvador',
  STL: 'St. Louis',
  SVX: 'Yekaterinburg',
  SYD: 'Sydney',
  SZV: '苏州',
  TBS: 'Tbilisi',
  TGU: 'Tegucigalpa',
  TLH: 'Tallahassee',
  TLL: 'Tallinn',
  TLV: 'Tel Aviv',
  TNA: '济南',
  TNR: 'Antananarivo',
  TPA: 'Tampa',
  TPE: 'Taipei ',
  TSN: '天津',
  TUN: 'Tunis',
  TXL: 'Berlin',
  UIO: 'Quito',
  ULN: 'Ulaanbaatar',
  URT: 'Surat Thani',
  VCP: 'Campinas',
  VIE: 'Vienna',
  VNO: 'Vilnius',
  VTE: 'Vientiane',
  WAW: 'Warsaw',
  WUH: '武汉',
  WUX: '无锡',
  XIY: '西安',
  YUL: 'Montréal',
  YVR: 'Vancouver',
  YWG: 'Winnipeg',
  YXE: 'Saskatoon',
  YYC: 'Calgary',
  YYZ: 'Toronto',
  ZAG: 'Zagreb',
  ZDM: 'Ramallah ',
  ZRH: 'Zürich',
}
